services:

  # Microservices
  apigateway:
    hostname: apigateway
    ports:
      - "16000:16000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16000
      - Authentication__Authority=http://auth.service:16100
      - Ocelot__Folder=Routes/docker
  
  auth.service:
    hostname: auth.service
    ports:
      - "16100:16100"
    depends_on:
      - authdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16100
      - ConnectionStrings__AuthDb=Host=authdb;Port=5432;Database=authdb;Username=admin;Password=admin;
      - Authentication__IdentityServerUrl=http://auth.service:16100
      - Authentication__IdentityServerTokenEndpoint=http://auth.service:16100/connect/token
  
  basket.service:
    hostname: basket.service
    ports:
      - "16200:16200"
    depends_on:
      - basketdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16200
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__BasketDb=Host=basketdb;Port=5432;Database=basketdb;Username=admin;Password=admin;
      - Authentication__Authority=http://auth.service:16100

  catalog.service:
    hostname: catalog.service
    ports:
      - "16300:16300"
    depends_on:
      - catalogdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16300
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__CatalogDb=Host=catalogdb;Port=5432;Database=catalogdb;Username=admin;Password=admin;
      - Authentication__Authority=http://auth.service:16100
  
  order.service:
    hostname: order.service
    ports:
      - "16400:16400"
    depends_on:
      - orderdb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16400
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__OrderDb=Host=orderdb;Port=5432;Database=orderdb;Username=admin;Password=admin;
      - Authentication__Authority=http://auth.service:16100
  
  # rabbitmq
  rabbitmq:
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  # Databases  
  authdb:
    hostname: authdb
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "16102:5432"
    volumes:
      - authdb-data:/var/lib/postgresql/data

  basketdb:
    hostname: basketdb
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: basketdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "16202:5432"
    volumes:
      - basketdb-data:/var/lib/postgresql/data

  catalogdb:
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "16302:5432"
    volumes:
      - catalogdb-data:/var/lib/postgresql/data
  
  orderdb:
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "16402:5432"
    volumes:
      - orderdb-data:/var/lib/postgresql/data

volumes:
  authdb-data:
  basketdb-data:
  catalogdb-data:
  orderdb-data:
      