services:
  customerdb:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - customerdb-data:/var/lib/postgresql/data

volumes:
  customerdb-data: