services:
  
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile

  product.service:
    image: product.service
    build:
      context: .
      dockerfile: src/Product.Service/Dockerfile

