services:

  # Microservices
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
  
  auth.service:
    image: ${DOCKER_REGISTRY-}auth.service
    build:
      context: .
      dockerfile: src/Auth.Service/Dockerfile
  
  basket.service:
    image: ${DOCKER_REGISTRY-}basket.service
    build:
      context: .
      dockerfile: src/Basket.Service/Dockerfile

  catalog.service:
    image: ${DOCKER_REGISTRY-}catalog.service
    build:
      context: .
      dockerfile: src/Catalog.Service/Dockerfile

  order.service:
    image: ${DOCKER_REGISTRY-}order.service
    build:
      context: .
      dockerfile: src/Order.Service/Dockerfile
  
  user.service:
    image: ${DOCKER_REGISTRY-}user.service
    build:
      context: .
      dockerfile: src/User.Service/Dockerfile
  
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
  
  # Databases  
  ecommercedb:
    image: postgres

volumes:
  ecommercedb_data:
      

