services:

  # Microservices
  apigateway:
    hostname: apigateway
    ports:
      - "16000:16000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16000
      - AuthOptions__Authority=http://auth.service:16100
      - OcelotOptions__Folder=Routes/docker
  
  auth.service:
    hostname: auth.service
    ports:
      - "16100:16100"
    depends_on:
      - ecommercedb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16100
      - AuthDbOptions__ConnectionString=Host=ecommercedb;Port=5432;Database=ecommercedb;Username=admin;Password=admin;
      - AuthOptions__IdentityServerUrl=http://auth.service:16100
      - AuthOptions__IdentityServerTokenEndpoint=http://auth.service:16100/connect/token
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
  
  basket.service:
    hostname: basket.service
    ports:
      - "16200:16200"
    depends_on:
      - ecommercedb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16200
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - BasketDbOptions__ConnectionString=Host=ecommercedb;Port=5432;Database=ecommercedb;Username=admin;Password=admin;
      - AuthOptions__Authority=http://auth.service:16100

  catalog.service:
    hostname: catalog.service
    ports:
      - "16300:16300"
    depends_on:
      - ecommercedb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16300
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - CatalogDbOptions__ConnectionString=Host=ecommercedb;Port=5432;Database=ecommercedb;Username=admin;Password=admin;
      - AuthOptions__Authority=http://auth.service:16100
  
  order.service:
    hostname: order.service
    ports:
      - "16400:16400"
    depends_on:
      - ecommercedb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16400
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - OrderDbOptions__ConnectionString=Host=ecommercedb;Port=5432;Database=ecommercedb;Username=admin;Password=admin;
      - AuthOptions__Authority=http://auth.service:16100
  
  user.service:
    hostname: user.service
    ports:
      - "16500:16500"
    depends_on:
      - ecommercedb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=16500
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - UserDbOptions_ConnectionString=Host=userdb;Port=5432;Database=userdb;Username=admin;Password=admin;
      - AuthOptions__Authority=http://auth.service:16100
  
  # rabbitmq
  rabbitmq:
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  # Databases  
  ecommercedb:
    hostname: ecommercedb
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ecommercedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "16002:5432"
    volumes:
      - ecommercedb-data:/var/lib/postgresql/data

volumes:
  ecommercedb-data:
      