// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product.Service.Data;

#nullable disable

namespace Product.Service.Migrations
{
    [DbContext(typeof(ProductItemContext))]
    partial class ProductItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Product.Service.Models.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a80248-0192-483b-8033-5cc9c2b63604"),
                            Description = "Description for Product 1",
                            Name = "Product 1",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("9406695f-6181-4a56-adce-ae94e6248b0c"),
                            Description = "Description for Product 2",
                            Name = "Product 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("e81e2dad-1fa2-4f04-9aa1-c6ad93b7a8e0"),
                            Description = "Description for Product 3",
                            Name = "Product 3",
                            Price = 300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
