// <auto-generated />
using Customer.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer.Service.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20240823060821_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customer.Service.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Email = "john-doe@gmail.com",
                            Name = "John Doe",
                            Phone = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            Email = "jane-doe@gmail.com",
                            Name = "Jane Doe",
                            Phone = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            Email = "bob.smith@gmail.com",
                            Name = "Bob Smith",
                            Phone = "1112223333"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Maple St",
                            Email = "alice.johnson@gmail.com",
                            Name = "Alice Johnson",
                            Phone = "4445556666"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Pine St",
                            Email = "charlie.brown@gmail.com",
                            Name = "Charlie Brown",
                            Phone = "7778889999"
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Cedar St",
                            Email = "emily.davis@gmail.com",
                            Name = "Emily Davis",
                            Phone = "2223334444"
                        },
                        new
                        {
                            Id = 7,
                            Address = "123 Birch St",
                            Email = "frank.wilson@gmail.com",
                            Name = "Frank Wilson",
                            Phone = "5556667777"
                        },
                        new
                        {
                            Id = 8,
                            Address = "456 Spruce St",
                            Email = "grace.lee@gmail.com",
                            Name = "Grace Lee",
                            Phone = "8889990000"
                        },
                        new
                        {
                            Id = 9,
                            Address = "789 Redwood St",
                            Email = "henry.clark@gmail.com",
                            Name = "Henry Clark",
                            Phone = "1112224444"
                        },
                        new
                        {
                            Id = 10,
                            Address = "321 Fir St",
                            Email = "isabella.martinez@gmail.com",
                            Name = "Isabella Martinez",
                            Phone = "3334445555"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
