global using AutoFixture;
global using MockQueryable;
global using Moq;
global using Microsoft.Extensions.Logging;
global using Basket.Service.Features.Queries.BasketQueries.GetAllBaskets;
global using Basket.Service.Repositories;
global using Basket.Service.Tests.Extensions;
global using Contracts.Services.Identity;
global using Moq;