// <auto-generated />
using System;
using Catalog.Service.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Service.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Service.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7557),
                            Description = "",
                            ImageUrl = "",
                            Name = "Áo thun",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7558)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7561),
                            Description = "",
                            ImageUrl = "",
                            Name = "Quần jean",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7562)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7563),
                            Description = "",
                            ImageUrl = "",
                            Name = "Giày thể thao",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7563)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7564),
                            Description = "",
                            ImageUrl = "",
                            Name = "Đồng hồ",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7564)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7565),
                            Description = "",
                            ImageUrl = "",
                            Name = "Túi xách",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7565)
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7566),
                            Description = "",
                            ImageUrl = "",
                            Name = "Mũ",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7567)
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7567),
                            Description = "",
                            ImageUrl = "",
                            Name = "Kính râm",
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7568)
                        });
                });

            modelBuilder.Entity("Catalog.Service.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AvailableStock = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7401),
                            Description = "Áo thun nam hàng hiệu màu đỏ",
                            ImageUrl = "",
                            Name = "Áo thun nam",
                            Price = 15m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7411)
                        },
                        new
                        {
                            ProductId = 2,
                            AvailableStock = 0,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7416),
                            Description = "Áo thun nữ hàng hiệu màu hồng",
                            ImageUrl = "",
                            Name = "Áo thun nữ",
                            Price = 20m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7416)
                        },
                        new
                        {
                            ProductId = 3,
                            AvailableStock = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7418),
                            Description = "Quần jean nam hàng hiệu màu xanh",
                            ImageUrl = "",
                            Name = "Quần jean nam",
                            Price = 30m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7418)
                        },
                        new
                        {
                            ProductId = 4,
                            AvailableStock = 0,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7419),
                            Description = "Quần jean nữ hàng hiệu màu xanh",
                            ImageUrl = "",
                            Name = "Quần jean nữ",
                            Price = 25m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7420)
                        },
                        new
                        {
                            ProductId = 5,
                            AvailableStock = 0,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7421),
                            Description = "Giày thể thao nam hàng hiệu màu trắng",
                            ImageUrl = "",
                            Name = "Giày thể thao nam",
                            Price = 50m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7421)
                        },
                        new
                        {
                            ProductId = 6,
                            AvailableStock = 0,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7422),
                            Description = "Giày thể thao nữ hàng hiệu màu trắng",
                            ImageUrl = "",
                            Name = "Giày thể thao nữ",
                            Price = 45m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7423)
                        },
                        new
                        {
                            ProductId = 7,
                            AvailableStock = 0,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7424),
                            Description = "Đồng hồ nam hàng hiệu màu đen",
                            ImageUrl = "",
                            Name = "Đồng hồ nam",
                            Price = 100m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7424)
                        },
                        new
                        {
                            ProductId = 8,
                            AvailableStock = 0,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7425),
                            Description = "Đồng hồ nữ hàng hiệu màu đen",
                            ImageUrl = "",
                            Name = "Đồng hồ nữ",
                            Price = 90m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7426)
                        },
                        new
                        {
                            ProductId = 9,
                            AvailableStock = 0,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7427),
                            Description = "Túi xách nam hàng hiệu màu nâu",
                            ImageUrl = "",
                            Name = "Túi xách nam",
                            Price = 70m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7427)
                        },
                        new
                        {
                            ProductId = 10,
                            AvailableStock = 0,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7428),
                            Description = "Túi xách nữ hàng hiệu màu nâu",
                            ImageUrl = "",
                            Name = "Túi xách nữ",
                            Price = 60m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7429)
                        },
                        new
                        {
                            ProductId = 11,
                            AvailableStock = 0,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7430),
                            Description = "Mũ nam hàng hiệu màu xanh",
                            ImageUrl = "",
                            Name = "Mũ nam",
                            Price = 10m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7430)
                        },
                        new
                        {
                            ProductId = 12,
                            AvailableStock = 0,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7431),
                            Description = "Mũ nữ hàng hiệu màu xanh",
                            ImageUrl = "",
                            Name = "Mũ nữ",
                            Price = 10m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7431)
                        },
                        new
                        {
                            ProductId = 13,
                            AvailableStock = 0,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7433),
                            Description = "Kính râm nam hàng hiệu màu đen",
                            ImageUrl = "",
                            Name = "Kính râm nam",
                            Price = 20m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7433)
                        },
                        new
                        {
                            ProductId = 14,
                            AvailableStock = 0,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7434),
                            Description = "Kính râm nữ hàng hiệu màu đen",
                            ImageUrl = "",
                            Name = "Kính râm nữ",
                            Price = 20m,
                            UpdatedDate = new DateTime(2024, 8, 26, 15, 55, 10, 723, DateTimeKind.Local).AddTicks(7434)
                        });
                });

            modelBuilder.Entity("Catalog.Service.Data.Models.Product", b =>
                {
                    b.HasOne("Catalog.Service.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalog.Service.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
